### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by bernatpl** [trevjonez/composer-gradle-plugin#13]
It is not working on Windows 7.
I also tried to add the dependency `composer "com.gojuno.composer:composer:0.3.0"`, which is supposed to have support for Windows, but it's also not working.

I get the following exception:
```
Exception in thread "main" java.lang.IllegalStateException: Unbuffered output is not supported on Windows
	at com.gojuno.commander.os.ProcessesKt$process$1.call(Processes.kt:61)
	at com.gojuno.commander.os.ProcessesKt$process$1.call(Processes.kt)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:72)
	at rx.internal.operators.OnSubscribeCreate.call(OnSubscribeCreate.java:32)
	at rx.Observable.unsafeSubscribe(Observable.java:10256)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bernatpl** [comment]
Probably related with https://github.com/gojuno/commander/issues/4

**Comment by trevjonez** [comment]
any further info on this? It is entirely possible I need to update something to make this windows friendly since I do a bit of file system shuffling.

**Comment by bernatpl** [comment]
It looks like there is a pending merge to fix this https://github.com/gojuno/commander/pull/14

**Comment by trevjonez** [comment]
give version 0.6.0 of the plugin a try and let me know if we need to do anything else to get this resolved.

**Comment by trevjonez** [comment]
Having not heard back I am going to close this. 

If you or anyone are effected by this still please provide any info possible and we will reopen it.
