### ISSUE TITLE
Composer 0.3.2 removed test runner param

### ISSUE THREAD

**Issue by plastiv** [trevjonez/composer-gradle-plugin#16]
Composer plugin 0.5.2 with composer 0.3.2 results in crash.

https://github.com/gojuno/composer/releases/tag/v0.3.2

```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--test-package' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.getMainParameter(JCommander.java:887)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:705)
	at com.beust.jcommander.JCommander.parse(JCommander.java:312)
	at com.beust.jcommander.JCommander.parse(JCommander.java:291)
	at com.gojuno.composer.ArgsKt.parseArgs(Args.kt:121)
	at com.gojuno.composer.MainKt.main(Main.kt:34)
```

**Comment by trevjonez** [comment]
0.6.0
